[default]
MONGODB_URI="@jinja mongodb://{{this.MONGO_ROOT_USER}}:{{this.MONGO_ROOT_PASS}}@{{this.MONGO_HOST}}:{{this.MONGO_PORT}}/{{this.MONGO_DB}}?authSource=admin"

# DEVELOPMENT
[development]

# MONGO CONFIGURAÇÕES IGUAL AO .ENV
MONGO_ROOT_USER="admin"
MONGO_ROOT_PASS="changeme"
MONGO_HOST="localhost"
MONGO_PORT=27017
MONGO_DB="apifastdb"

aws_access_key_id = ''
aws_secret_access_key = ''
telegram_token = ""
telegram_chat_id = 0
SMTP_HOST = "0.0.0.0"
SMTP_PORT = "1025"
SMTP_USER = ""
SMTP_PASSWORD = ""
SMTP_MSG_FROM = ""
# Server Local MAILHOG
SMTP_TLS = false



# PRODUCTION
[production]
aws_access_key_id = ''
aws_secret_access_key = ''
telegram_token = ""
telegram_chat_id = 0
SMTP_HOST = ""
SMTP_PORT = "587"
SMTP_USER = ""
SMTP_PASSWORD = ""
SMTP_MSG_FROM = ''

MONGO_ROOT_USER="admin_prod"
MONGO_ROOT_PASS="changeme"
MONGO_HOST="localhost"
MONGO_PORT=27017
MONGO_DB="apifastdb"
