version: '3.8'

services:
  mongo-fastapi:
    image: mongo:5.0
    container_name: mongo
    env_file: .env
    restart: unless-stopped
    environment:
      - PUID= 1000
      - PGID= 1000
      - MONGO_INITDB_ROOT_USERNAME=${DYANCONF_MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DYANCONF_MONGO_ROOT_PASS}
      - MONGO_INITDB_DATABASE="apifastdb"
    ports:
      - 27017:27017
    volumes:
      - $HOME/.docker/database/mongodb_proj_modelo:/data/db

  mongo-express:
    image: mongo-express
    container_name: moexpress
    ports:
      - 8086:8081
    env_file: .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DYANCONF_MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DYANCONF_MONGO_ROOT_PASS}
      - ME_CONFIG_MONGODB_URL=${DYANCONF_MONGODB_URI}
      - ME_CONFIG_BASICAUTH_USERNAME=${DYANCONF_MOGOEXPRESS_BASICAUTH_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${DYANCONF_MONGOEXPRESS_BASICAUTH_PASS}
    links:
      - mongo-fastapi
    restart: unless-stopped
